db_host: "{{ hostvars[groups['db'][0]].inventory_hostname }}"
mongo_bind_ip: 0.0.0.0
env: prod
nginx_sites:
  default:
    - listen 80
    - server_name "reddit"
    - |
      location / {
        proxy_pass http://127.0.0.1:9292;
      }
