---
- name: Show info about the env this host belows to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment!!!"
- name: Change mongo config file
  ansible.builtin.template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    mode: U=rw, G=r, O=r
  notify: Restart mongod
