---
- name: Deploy application
  hosts: app
  vars:
    deploy_user: appuser
  tasks:
    - name: APT Install
      become: true
      apt:
        name: git
        state: present
        update_cache: true

    - name: Fetch the latest version of application code
      git:
        repo: "https://github.com/express42/reddit.git"
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      notify: Reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"

  handlers:
    - name: Reload puma
      become: true
      systemd:
        name: puma
        state: restarted
